### ISSUE TITLE
Mocking Static Methods documentation seems misleading

### ISSUE THREAD

**Issue by elazar** [mlively/Phake#184]
> In this case, because the `static::` keyword will cause the called class to be determined at runtime, you will be able to verify and stub calls to `StaticFactory::factory()`.

[Source](http://phake.readthedocs.org/en/2.1/mocking-statics.html)

This doesn't seem accurate. Calls to `StaticFactory::getInstance()` are still bound to that class name and will still invoke the `StaticFactory` version of `factory()`. You can create a mock of `StaticFactory` and stub `factory()` on that object's class, in which case the use of `static::` in `getInstance()` will resolve to the mock's version of `factory()`, but only if `getInstance()` is called using the mock's class name.

None of this seems like it would be useful unless one of these scenarios applies:

1. The class containing the static method being stubbed is also the class under test, in which case we're involving either partial mocks or the `thenCallParent()` answer, which the documentation notes are both intended for legacy code where the section on mocking static methods contains no similar reference to legacy code.
2. The static method being stubbed is invoked by the code under test where the class off of which that invocation takes place is variable and configurable.

Would appreciate any feedback you can provide. I'm completely open to the possibility that I'm just lost when it comes to using this feature as intended. :)

**Comment by mlively** [comment]
This is just really poorly documented. It works largely based on LSB functionality in PHP. So there is a bit of finagling you have to do to in order to get it to work correctly beyond only using it in the code under test.

The basic gist of this is that you need to create a seam for your static methods. Thankfully in php now you can do something along the lines of $myVar::myStatic() where if $myVar is a string it resolves as you would think for a static method. The useful piece though is that if $myVar is an object, it will resolve that object down to the classname and use that for the static.

So, the general idea here is that you can take code that is in class Foo:

```php
class Foo
{
    public function doSomething()
    {
        // ... code that does stuff ...
        Logger::logData();
    }
}
```

which does not provide a seam for mocking Logger::logData() and provide that seem by changing it to:

```php
class Foo
{
    public $logger = 'Logger';
    public function doSomething()
    {
        // ... code that does stuff ...
        $logger = $this->logger;
        $logger::logData($data);
    }
}
```

Now you can mock logData as follows:

```php
class FooTest
{
    public function testDoSomething()
    {
        $foo = new Foo();
        $foo->logger = Phake::mock('Logger');
        $foo->doSomething();
        Phake::verify($foo->logger)->logData(Phake::anyParameter());
    }
}
```

Don't trust any of the above code, I am not somewhere where I can test it, but hopefully it conveys the general idea of how this is all supposed to work. I'll tighten it up and drop this into the documentation to provide more clarity.

**Comment by elazar** [comment]
@mlively Been a while. Have the docs been updated, or will they be?

**Comment by mlively** [comment]
@elazar take a look and let me know what you think of the documentation. I just pushed my use case example into the existing docs, I think it flows okay. Would love feedback.

**Comment by elazar** [comment]
@mlively Hm, tried running the example provided above and got this:

```
Fatal error: Uncaught exception 'Phake_Exception_VerificationException' with message 'Expected Logger->logData(<any parameters>) to be called exactly <1> times, actually called <0> times. In fact, there are no interactions with this mock.'
```

**Comment by shaikhul** [comment]
@mlively @elazar it seems mocking static method works but after reseting the mock I can't get expected response from actual static method, mind having a look into the last assertion ?

```php
class Bar {
    public static function baz() {
        return 'Baz';
    }
}

class Foo {
    public $bar = 'Bar';

    public function doBaz() {
        $bar = $this->bar;
        return $bar::baz();
    }
}

function test_phake_static() {
    $foo = new Foo;
    $foo->bar = Phake::mock('Bar');
    Phake::whenStatic($foo->bar)->baz()->thenReturn('Bat');

    $val = $foo->doBaz();
    Phake::verifyStatic($foo->bar)->baz();
    // this assertion works 
    if ($val !== 'Bat') {
        throw new Exception('Expected Bat, got' . $val);
    }

    // it seems $foo->bar is not resetting properly!
    Phake::resetStatic($foo->bar);

    $val = $foo->doBaz();
    // this assertion does not work!
    if ($val !== 'Baz') {
        throw new Exception('Expected Baz, got' . $val);
    }
}
```

**Comment by shaikhul** [comment]
@mlively I have opened a [PR](https://github.com/mlively/Phake/pull/219) to address this
