### ISSUE TITLE
inOrder() failing for multiple method calls with same parameters

### ISSUE THREAD

**Issue by kore** [mlively/Phake#193]
To demonstrate the issue I created a pull request with a failing test case showing the problem: https://github.com/mlively/Phake/pull/192 – I guess the PR describes the issue sufficiently, otherwise I can also describe it in further detail.

**Comment by bfeaver** [comment]
Based on the PR, it's failing because you're calling `foo('foo')` twice. The default behavior for a `verify()` call is that it is only called one time. It's the same as if we wrote:
```php
Phake::verify($mock1, Phake::times(1))->foo("foo");
```
If you instead change it to:
```php
Phake::verify($mock1, Phake::times(2))->foo("foo");
// or...
Phake::verify($mock1, Phake::atLeast(1))->foo("foo");
```
Then the tests pass correctly. I didn't see anything wrong with the assertion (it was actually failing because you were calling it twice, and it was expecting it once). But if you find another scenario where this is the case, feel free to reopen this issue.

**Comment by kore** [comment]
Thanks for clarifying my misunderstanding. Keep up the great work.
