### ISSUE TITLE
PSR-4 vs PSR-0 issue with Phake 3.1.3

### ISSUE THREAD

**Issue by mattsimpson** [mlively/Phake#270]
I am having an issue with the latest 3.1.3 release that I've traced back to this change: 5208167c10f3c0b8e87066d6d5b41e6b754bd4d4

Nearly all of my unit tests are failing. The following test is an example:

```
    public function testPhake() {
        if (class_exists('PHPUnit\Framework\TestCase')) {
            echo "This class exists: " . PHPUnit_Runner_Version::id(); // outputs 5.7.27
            echo "\n\n";
            echo "This results in a PHP error: " . PHPUnit\Runner\Version::id(); // see below
        } else {
            echo "Class does not exist";
        }
        exit;
    }
```

This test outputs:

```
This class exists: 5.7.27

This throws a PHP error:

Error: Class 'PHPUnit\Runner\Version' not found

core/library/vendor/phake/phake/src/Phake.php:573
core/library/vendor/phake/phake/src/Phake.php:180
unit-tests/models/RepositoryTest.php:64
```

What this is telling me is that the PSR-4 `PHPUnit\Framework\TestCase` class exists, but `PHPUnit\Runner\Version` does not; however, `PHPUnit_Runner_Version` as PSR-0 works.

I'm confused.

**Comment by bfeaver** [comment]
Can you tell me exactly what version of PHP and PHPUnit you're using? The other thought I had was to actually check for the `PHPUnit\Runner\Version` class instead of `*\TestCase`. But I wouldn't have thought that was mixing.

**Comment by mattsimpson** [comment]
Hi there. It's PHP 7.1.16 right now.

**Comment by bfeaver** [comment]
The issue is that in PHPUnit 5.7.27, they have a forward compatibility class for `PHPUnit\Framework\TestCase` so that both classes exist at the same time. The goal in changing the order in 5208167c10f3c0b8e87066d6d5b41e6b754bd4d4, was to make it so that in the instance where there was a class alias, it should use the newer version. However this assumed the newer version is just namespacing the old version and not vice-versa. We only test on PHPUnit >6, which I'm guessing is in part because <6 is deprecated and out of support. Our tests had issues when I tried to run it again 5.7.27.

For now, I'd suggest using `Phake::setClient(Phake::CLIENT_PHPUNIT)` in a common bootstrap for your test suite. This way you bypass the auto-detection for what client is being used.

When I get more time, I'll try getting PHPUnit 5.7 running with Travis and our tests.

**Comment by mattsimpson** [comment]
Maybe what I'll do is figure out why the heck we're using PHPUnit 5.7 :) Thanks very much. Take care.
